# Generated by Django 4.2.2 on 2023-06-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('change_user', 'Can change users'),)},
        ),
    ]
